/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aplex_JniBase_I2CController */

#ifndef _Included_com_aplex_JniBase_I2CController
#define _Included_com_aplex_JniBase_I2CController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aplex_JniBase_I2CController
 * Method:    open
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_aplex_JniBase_I2CController_open
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_aplex_JniBase_I2CController
 * Method:    readStr
 * Signature: (IIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aplex_JniBase_I2CController_readStr
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_aplex_JniBase_I2CController
 * Method:    writeStr
 * Signature: (IIILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_aplex_JniBase_I2CController_writeStr
  (JNIEnv *, jobject, jint, jint, jint, jstring, jint);

/*
 * Class:     com_aplex_JniBase_I2CController
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_aplex_JniBase_I2CController_close
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_aplex_JniBase_I2CController
 * Method:    readSoftID
 * Signature: (IIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aplex_JniBase_I2CController_readSoftID
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
