/* DO NOT EDIT THIS FILE - it is machine generated */
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <string.h>
#include <jni.h>

#include "android/log.h"
static const char *TAG="GPIO_MIO";
#define LOGE(fmt, args...) __android_log_print(ANDROID_LOG_ERROR, TAG, fmt, ##args)
/*
 * Class:     com_android_gpio_AplexGPIO
 * Method:    open
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_aplex_JniBase_AplexGPIO_open
  (JNIEnv *env, jobject thiz, jstring path, jint flags){
	int fd = -1;
	// Opening device
	{
		jboolean iscopy;
		const char *path_utf = (*env)->GetStringUTFChars(env, path, &iscopy);
		LOGE("Opening serial port %s with flags 0x%x", path_utf, O_RDWR | flags);
		fd = open(path_utf, O_RDWR | flags);
		LOGE("open() fd = %d", fd);
		(*env)->ReleaseStringUTFChars(env, path, path_utf);
		if (fd == -1)
		{
			// Throw an exception
			LOGE("Cannot open port");
			// TODO: throw an exception
			return -1;
		}
	}

	return (jint)fd;
}

/*
 * Class:     com_android_gpio_AplexGPIO
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_aplex_JniBase_AplexGPIO_close
  (JNIEnv *env, jobject thiz, jint fd){
	close( (int)fd );
	LOGE("close() fd = %d", fd);
}

/*
 * Class:     com_android_gpio_AplexGPIO
 * Method:    ioctl
 * Signature: (III)V
 */
JNIEXPORT jlong JNICALL Java_com_aplex_JniBase_AplexGPIO_ioctl
  (JNIEnv *env, jobject thiz, jint fd, jint cmd, jint value){
  	//LOGE("ioctl() fd = %d, cmd = %d, value = %d", fd, cmd, value);
	return ioctl(fd, cmd, value);
}
