/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aplex_JniBase_AplexBuzz */

#ifndef _Included_com_aplex_JniBase_AplexBuzz
#define _Included_com_aplex_JniBase_AplexBuzz
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aplex_JniBase_AplexBuzz
 * Method:    enable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aplex_JniBase_AplexBuzz_enable
  (JNIEnv *, jclass);

/*
 * Class:     com_aplex_JniBase_AplexBuzz
 * Method:    setFrequency
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_aplex_JniBase_AplexBuzz_setFrequency
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_aplex_JniBase_AplexBuzz
 * Method:    disable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aplex_JniBase_AplexBuzz_disable
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
